/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package School;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author John YK
 */
public class Register_staff extends javax.swing.JFrame {

    /**
     * Creates new form Register_staff
     */
    Connection connection=null;
    PreparedStatement pst=null;
    PreparedStatement stm=null;
    PreparedStatement verify=null;
    ResultSet rs=null;


    public Register_staff() {
    this.setUndecorated(true);
    this.setAlwaysOnTop(true);
    this.setResizable(false);        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_fn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_pn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField_ln = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        Answer = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pass2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        HoverBar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 575, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STAFF REGISTRATION FORM");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 300, -1));

        jTextField_id.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });
        jTextField_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_idKeyTyped(evt);
            }
        });
        jPanel3.add(jTextField_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 172, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("ID Number");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, 20));

        jTextField_fn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fnActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 172, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("First Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 90, 20));

        uname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 172, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Username");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 90, -1));

        jTextField_pn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_pn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_pnKeyTyped(evt);
            }
        });
        jPanel3.add(jTextField_pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 172, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, 21));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton1.setText("MALE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 80, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Gender");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 60, 21));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton3.setText("FEMALE");
        jPanel3.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 85, -1));

        jTextField_ln.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jTextField_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 172, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 90, 16));
        jPanel3.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 170, 30));

        Answer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Answer.setText("Answer");
        jPanel3.add(Answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 70, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE QUESTION", "Which Primary school did you attend?", "What is your father's name?", "What is your pet?", "What is your favourite game?" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 270, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Security Question");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 140, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT COUNTRY", "KENYA", "UGANDA", "ETHIOPIA", "SOMALIA", "SUDAN", "DJIBOUTI", "CAMEROON", "TANZANIA", "SOUTH AFRICA", "ERITREA", "NIGERIA", "LIBYA", "GHANA", "RWANDA", " " }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 171, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Country");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 70, 20));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("<<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 110, 40));

        pass2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 172, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Repeat Password");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, 30));

        pass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 172, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Password");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 70, 20));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 120, 40));

        HoverBar.setBackground(new java.awt.Color(255, 255, 204));
        HoverBar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        HoverBar.setForeground(new java.awt.Color(255, 0, 0));
        HoverBar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HoverBar.setBorder(null);
        HoverBar.setOpaque(false);
        HoverBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoverBarActionPerformed(evt);
            }
        });
        jPanel3.add(HoverBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 420, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jTextField_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(! (Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_idKeyTyped

    private void jTextField_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnActionPerformed

    private void jTextField_pnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_pnKeyTyped
        char k=evt.getKeyChar();
        if(! (Character.isDigit(k) || (k==KeyEvent.VK_BACKSPACE) || k==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_pnKeyTyped

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String fn,ln,query,gn,cn,un,ps,ps2,id,pn,an,qn;
        id= jTextField_id.getText();
        fn=jTextField_fn.getText();
        ln=jTextField_ln.getText();
        pn=jTextField_pn.getText();
        un=uname.getText();
        ps=pass.getText();
        ps2=pass2.getText();
        cn=jComboBox1.getSelectedItem().toString();
        qn= jComboBox2.getSelectedItem().toString();
        an= ans.getText();
        if (jRadioButton1.isSelected()){
            gn="MALE";

        }else{
            gn="FEMALE";

        }
        query= "insert into staff values(?,?,?,?,?,?,?,?,?);";
        String query2="insert into login values(?,?,?,?)";
        String query3="select * from login where username=? and passwrd=?;";

        try{
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/registration","root","jnjg5//9");
            verify=connection.prepareStatement(query3);
            verify.setString(1, un);
            verify.setString(2, ps);
            rs=verify.executeQuery();
            if (rs.next()){
                HoverBar.setText("A user with that name already exists,please login or use a different name!");

            }else if (id.equals("")){
                HoverBar.setText("Please enter ID number!");
                jTextField_id.requestFocus();
            }else if (fn.equals("")){
                HoverBar.setText("Please enter your first name!");
                jTextField_fn.requestFocus();
            }else if (ln.equals("")){
                HoverBar.setText("Please enter your last name!");
                jTextField_ln.requestFocus();
            }else if (un.equals("")){
                HoverBar.setText("Please enter a username!");
                uname.requestFocus();
            }else if (pn.equals("")){
                HoverBar.setText("Please enter your phone number!");
                jTextField_pn.requestFocus();
            }else if (!(jRadioButton1.isSelected() | jRadioButton3.isSelected())){
                HoverBar.setText("Please select gender!");
            }else if ((jRadioButton1.isSelected() && jRadioButton3.isSelected())){
                HoverBar.setText("Only one option can be selected under 'gender'");
            }else if (ps.equals("")){
                HoverBar.setText("Please enter a password!");
                pass.requestFocus();
            }else if (ps2.equals("")){
                HoverBar.setText("Please confirm the password!");
                pass2.requestFocus();
            }else if(! ps.equals(ps2)){
                HoverBar.setText("Passwowd do not match!");
                pass.requestFocus();
            }else if (cn.equalsIgnoreCase("select country")){
                HoverBar.setText("Please choose a country!");
                jComboBox1.requestFocus();

            }else if (qn.equalsIgnoreCase("choose question")){
                HoverBar.setText("You have to choose a security question");
                jComboBox2.requestFocus();

            }else if (an.equals("")){
                HoverBar.setText("Provide an answer to the security question!");
                ans.requestFocus();

            }
            else {
                pst=connection.prepareStatement(query);
                pst.setString(1,id);
                pst.setString(2,fn);
                pst.setString(3,ln);
                pst.setString(4,un);
                pst.setString(5,pn);
                pst.setString(6,ps);
                pst.setString(7,gn);
                pst.setString(8,cn);
                pst.setString(9,an);
                pst.executeUpdate();
                stm=connection.prepareStatement(query2);
                stm.setString(1,id);
                stm.setString(2,un);
                stm.setString(3,an);
                stm.setString(4,ps);
                stm.executeUpdate();
                HoverBar.setText("");
                HoverBar.setForeground(Color.green);
                HoverBar.setText("Registration successful");
            }
        }
        catch (SQLException ex) {
            HoverBar.setForeground(Color.red);
            HoverBar.setText("sqlError");
            System.out.println(ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void HoverBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoverBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoverBarActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Answer;
    private javax.swing.JTextField HoverBar;
    private javax.swing.JTextField ans;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField_fn;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_ln;
    private javax.swing.JTextField jTextField_pn;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
