/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package School;

import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JPanel;

/**
 *
 * @author John YK
 */
public class Reset_pass extends javax.swing.JFrame {
            final JPanel panel = new JPanel();

    Connection conn=null;
    PreparedStatement pst=null;
    PreparedStatement stm= null;
    PreparedStatement pr = null;
    ResultSet rs=null;

    /**
     * Creates new form Reset_pass
     */
    public Reset_pass() {
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.rs = null;
        initComponents();
        Toolkit tk= Toolkit.getDefaultToolkit();
            int xsize= (int) tk.getScreenSize().getWidth();
            int ysize= (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ans = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        question = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        idnum = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        correct = new javax.swing.JTextField();
        incorrect = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 378, 188, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 51, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Password reset Form");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 230, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel3.setText("Security Question");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 110, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel4.setText("Answer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 70, 22));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 500, 110, -1));
        jPanel1.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 168, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel5.setText("New Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel6.setText("Repeat password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));
        jPanel1.add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 169, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 169, -1));

        question.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Which Primary school did you attend?", "What is your father's name?", "What is your pet?", "What is your favourite game?", " " }));
        jPanel1.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 253, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel7.setText("Username");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 67, -1));
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 168, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel8.setText("ID Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 70, -1));

        idnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idnumKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idnumKeyTyped(evt);
            }
        });
        jPanel1.add(idnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 168, -1));

        jButton3.setBackground(new java.awt.Color(0, 255, 102));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Back to Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 110, -1));

        correct.setEditable(false);
        correct.setBackground(new java.awt.Color(255, 255, 255));
        correct.setForeground(new java.awt.Color(0, 153, 0));
        correct.setBorder(null);
        correct.setOpaque(false);
        correct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctActionPerformed(evt);
            }
        });
        jPanel1.add(correct, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 360, 20));

        incorrect.setForeground(new java.awt.Color(255, 0, 0));
        incorrect.setBorder(null);
        incorrect.setOpaque(false);
        incorrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectActionPerformed(evt);
            }
        });
        jPanel1.add(incorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 360, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
String un, qn, an, ps,ps2, query,query2,query3,id;
        un= uname.getText();
//        qn=question.getSelectedItem().toString();
        an= ans.getText();
        ps= pass.getText();
        ps2= pass2.getText();
        id= idnum.getText();

        query= "select * from login where ID=? and answer=?";
        query2= "update staff SET pass =? where ID=? and username=?";
        query3= "update login set passwrd=? where ID=? and username=?";
        
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/registration","root","jnjg5//9");
                pst= conn.prepareStatement(query);
                pst.setString(1,id);
                pst.setString(2, an);
                rs=pst.executeQuery();

         if (rs.next() && ps.equals(ps2)){
                pr= conn.prepareStatement(query2);
                pr.setString(1, ps);
                pr.setString(2, id);
                pr.setString(3, un);
                int data1= pr.executeUpdate();
                
                    stm= conn.prepareStatement(query3);
                    stm.setString(1, ps);
                    stm.setString(2, id);
                    stm.setString(3, un);
//                    stm.executeUpdate();
                int data2= stm.executeUpdate();
         
                if (data1>0 && data2>0){
                correct.setText("Reset successful, click back to return to login page");
                incorrect.setText("");
                
              } else { 
              incorrect.setText("Reset failed!,please review details");
              correct.setText("");
                }
         }else { 
              incorrect.setText("Reset failed!,please review details");
              correct.setText("");
                }
            }catch (HeadlessException | SQLException ex) {
            incorrect.setText("sqlError");
            System.out.println(ex);


        }                              
        
            


    }//GEN-LAST:event_jButton1ActionPerformed

    private void incorrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incorrectActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        Login third= new Login();
        third.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void correctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctActionPerformed

    private void idnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idnumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnumKeyPressed

    private void idnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idnumKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(! (Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_DELETE)){
             evt.consume();
        }
    
    }//GEN-LAST:event_idnumKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reset_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reset_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reset_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reset_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reset_pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans;
    private javax.swing.JTextField correct;
    private javax.swing.JTextField idnum;
    private javax.swing.JTextField incorrect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JComboBox<String> question;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
