/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package School;

/**
 *
 * @author John YK
 */
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

public class Staff extends javax.swing.JFrame {

    /**
     * Creates new form Staff_details
     */
    public Staff() {
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        initComponents();
        Toolkit tk= Toolkit.getDefaultToolkit();
            int xsize= (int) tk.getScreenSize().getWidth();
            int ysize= (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
    }
        public Staff(String staffno) {
        ResultSet rs= null;
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        initComponents();
        Toolkit tk= Toolkit.getDefaultToolkit();
            int xsize= (int) tk.getScreenSize().getWidth();
            int ysize= (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        if (staffno.equals("0")){
        String query2;
        query2="select * from staff";
        try{
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","");
            PreparedStatement pst=connection.prepareStatement(query2);
            rs=pst.executeQuery();
            while (rs.next()){

                int id = rs.getInt("ID");
                String fname = rs.getString("FIRST_NAME");
                String lname = rs.getString("LAST_NAME");
                String uname = rs.getString("USERNAME");
                int pn = rs.getInt("PHONE");
                String ps = rs.getString("PASS");
                String gn = rs.getString("GENDER");
                String cn = rs.getString("COUNTRY");                
                String an = rs.getString("answer");
                
                DefaultTableModel model= (DefaultTableModel)staff_details.getModel();
                Object[] row = new Object[9];
                row[0]= id;
                row[1]=fname;
                row[2]=lname;
                row[3]=uname;
                row[4]=pn;
                row[5]=ps;
                row[6]=gn;   
                row[7]=cn;
                row[8]=an;  
                model.addRow(row);
            }
        }catch (SQLException ex) {
            hover_staff.setText("sqlError");
            System.out.println(ex);
        }
                    if (staff_details.getRowCount()<1){
                    hover_staff.setText("No data found");
                }
        }else{
          String query2="select * from staff where ID=?";
        try{
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","");
            PreparedStatement pst=connection.prepareStatement(query2);
            pst.setString(1,staffno);
            rs=pst.executeQuery();
            while (rs.next()){

                int id = rs.getInt("ID");
                String fname = rs.getString("FIRST_NAME");
                String lname = rs.getString("LAST_NAME");
                String uname = rs.getString("USERNAME");
                int pn = rs.getInt("PHONE");
                String ps = rs.getString("PASS");
                String gn = rs.getString("GENDER");
                String cn = rs.getString("COUNTRY");                
                String an = rs.getString("answer");
                
                DefaultTableModel model= (DefaultTableModel)staff_details.getModel();
                Object[] row = new Object[9];
                row[0]= id;
                row[1]=fname;
                row[2]=lname;
                row[3]=uname;
                row[4]=pn;
                row[5]=ps;
                row[6]=gn;   
                row[7]=cn;
                row[8]=an;  
                model.addRow(row);
            }
                    if (staff_details.getRowCount()<1){
                    hover_staff.setText("No data found");
                }
        }catch (SQLException ex) {
            hover_staff.setText("sqlError");
            System.out.println(ex);
        }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        staff_details = new javax.swing.JTable();
        hover_staff = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staff_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FName", "LName", "Username", "Phone", "password", "Gender", "Country", "Answer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(staff_details);
        if (staff_details.getColumnModel().getColumnCount() > 0) {
            staff_details.getColumnModel().getColumn(0).setResizable(false);
            staff_details.getColumnModel().getColumn(1).setResizable(false);
            staff_details.getColumnModel().getColumn(2).setResizable(false);
            staff_details.getColumnModel().getColumn(4).setResizable(false);
            staff_details.getColumnModel().getColumn(5).setResizable(false);
            staff_details.getColumnModel().getColumn(6).setResizable(false);
            staff_details.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 1010, 580));

        hover_staff.setEditable(false);
        hover_staff.setBackground(new java.awt.Color(255, 204, 204));
        hover_staff.setForeground(new java.awt.Color(255, 0, 51));
        hover_staff.setBorder(null);
        jPanel1.add(hover_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 260, -1));

        jLabel1.setBackground(new java.awt.Color(255, 0, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STAFF DETAILS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 130, -1));

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Home");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel2.add(jLabel2);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(Color.green);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(new java.awt.Color(0, 204,204));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hover_staff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable staff_details;
    // End of variables declaration//GEN-END:variables
}
