/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package School;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
/**
 *
 * @author John YK
 */
public class Students extends javax.swing.JFrame {

    /**
     * Creates new form Students
     */
Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    
    public Students() {
                this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        initComponents();
        Toolkit tk= Toolkit.getDefaultToolkit();
            int xsize= (int) tk.getScreenSize().getWidth();
            int ysize= (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
    }
    public Students(String admission) {
        
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        initComponents();
        Toolkit tk= Toolkit.getDefaultToolkit();
            int xsize= (int) tk.getScreenSize().getWidth();
            int ysize= (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
          if (admission.equals("0")){        
          String query2;

        query2="select * from students";
        try{
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","");
            PreparedStatement pst=connection.prepareStatement(query2);
            rs=pst.executeQuery();
            while (rs.next()){

                String adm = rs.getString("Adm");
                String fname = rs.getString("First_name");
                String mname = rs.getString("Middle_name");
                String lname = rs.getString("Last_name");
                int id = rs.getInt("ID_Number");
                int tel = rs.getInt("Tel");
                String gender = rs.getString("Gender");
                
                DefaultTableModel model= (DefaultTableModel)jTable_students.getModel();
                Object[] row = new Object[7];
                row[0]= adm;
                row[1]=fname;
                row[2]=mname;
                row[3]=lname;
                row[4]=id;
                row[5]=tel;
                row[6]=gender;                
                model.addRow(row);
            }
                    if (jTable_students.getRowCount()<1){
                    hover_students.setText("No students registered yet");
                }
        }catch (SQLException ex) {
            hover_students.setText("sqlError");
            System.out.println(ex);
        }
    }else{
        String query2;

        query2="select * from students where Adm=?";
        try{
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","");
            PreparedStatement pst=connection.prepareStatement(query2);
            pst.setString(1, admission);
            rs=pst.executeQuery();
            while (rs.next()){

                String adm = rs.getString("Adm");
                String fname = rs.getString("First_name");
                String mname = rs.getString("Middle_name");
                String lname = rs.getString("Last_name");
                int id = rs.getInt("ID_Number");
                int tel = rs.getInt("Tel");
                String gender = rs.getString("Gender");
                
                DefaultTableModel model= (DefaultTableModel)jTable_students.getModel();
                Object[] row = new Object[7];
                row[0]= adm;
                row[1]=fname;
                row[2]=mname;
                row[3]=lname;
                row[4]=id;
                row[5]=tel;
                row[6]=gender;                
                model.addRow(row);
            }            
            if (jTable_students.getRowCount()<1){
                    hover_students.setText("No matches found");
                }
        }catch (SQLException ex) {
            hover_students.setText("sqlError");
            System.out.println(ex);
        }
    }
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        students_report1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_students = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        hover_students = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        students_report1.setBackground(new java.awt.Color(255, 204, 204));
        students_report1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adm No", "First Name", "Middle Name", "Last Name", "ID Number", "Phone Number", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_students);

        students_report1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 820, 600));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("STUDENT DETAILS");
        students_report1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 170, -1));

        hover_students.setEditable(false);
        hover_students.setBackground(new java.awt.Color(255, 204, 204));
        hover_students.setForeground(new java.awt.Color(255, 0, 0));
        hover_students.setBorder(null);
        students_report1.add(hover_students, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 260, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Back to home");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2);

        students_report1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 90, 30));

        getContentPane().add(students_report1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(Color.green);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(Color.white);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Students().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hover_students;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_students;
    private javax.swing.JPanel students_report1;
    // End of variables declaration//GEN-END:variables
}
